### ISSUE TITLE
bug: Transformed url does not respect custom slug

### ISSUE THREAD

**Issue by techfg** [vernak2539/astro-rehype-relative-markdown-links#14]
When a page contains a custom slug, the transformed url is not respecting it and instead, generating the `astro default` slug via `githug-slugger`.

For example, in a file `/posts/post-3.md`:

```markdown
---
title: Post 3
slug: post.3
---

[Post 3](./post-3.md)
```

Should result in `/posts/post.3` but instead results in `/posts/post3`.

It appears in #9 logic was added to handle special characters, etc. which makes sense and was needed.  However, if a custom slug exists, it should use it. 

Astro [appears to handle this](https://github.com/withastro/astro/blob/ecb44351e98cfba575447699689b0ace49cd3c9d/packages/astro/src/content/utils.ts#L473) by generating the default slug but then checking for a custom slug and if exists, using it, else falling back on default.

Repro:
- <https://stackblitz.com/edit/withastro-astro-7ge5gz>

With Proposed Fixes from PR #21:
- <https://stackblitz.com/edit/withastro-astro-mtqt5k>

Steps to repro:
1. Open repro
2. Click on `Post 1` link
3. Click on either link under `Repro for Issue #14`

Expected Result:
Link should navigate to `/posts/post.3` or `/posts/archive.md/archive-1` (depending on link chosen)

Actual Result:
The `.` is stripped and results in 404

Additional Info:
You can see all links that Astro generates on home page under `Issue #14` heading

**Comment by techfg** [comment]
FYI - Edited OP to a [Stackblitz](https://stackblitz.com/edit/github-pdzrjo-qnmg8l) to the repro that contains the proposed fixes from #21.

**Comment by vernak2539** [comment]
Released in [v0.9.0](https://www.npmjs.com/package/astro-rehype-relative-markdown-links/v/0.9.0)! Thanks!
