### ISSUE TITLE
bug: Content collection path segment is slugified

### ISSUE THREAD

**Issue by techfg** [vernak2539/astro-rehype-relative-markdown-links#15]
When a url is transformed, the content collection path segment is being slugified resulting in incorrect path being generated.

For example, in a content collection of `/posts.md`, in a file `post-3.md`, the resulting url will be `/postsmd/post-3` when it should be `/posts.md/post-3.

Astro [does not appear to slugify](https://github.com/withastro/astro/blob/ecb44351e98cfba575447699689b0ace49cd3c9d/packages/astro/src/content/utils.ts#L238) the content collection segment itself, only the path relative to it.

Repro:
- <https://stackblitz.com/edit/withastro-astro-7ge5gz>

With Proposed Fixes from PR #21:
- <https://stackblitz.com/edit/withastro-astro-mtqt5k>

Steps to repro:

1. Open repro
2. Click on `Post MD 1`
3. Click on either link under `Repro for Issue #15`

Expected Result:
Link should navigate to `/posts.md/post-md-1` or `/posts.md/post.md.2` (has a custom slug) depending on which link you clicked.

Actual Result:
`/posts.md` is sluggified to `/postsmd` resulting in 404

Additional Info:
You can see all links that Astro generates on home page under `Issue #15` heading

**Comment by techfg** [comment]
FYI - Edited OP to a [Stackblitz](https://stackblitz.com/edit/github-pdzrjo-qnmg8l) to the repro that contains the proposed fixes from #21.

**Comment by vernak2539** [comment]
Released in [v0.9.0](https://www.npmjs.com/package/astro-rehype-relative-markdown-links/v/0.9.0)! Thanks!
